apiVersion: apps/v1
kind: Deployment
metadata:
  name: chating-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chating-app
  template:
    metadata:
      labels:
        app: chating-app
    spec:
      containers:
      - name: chating-app
        image: derkal/chating-appbackend:latest
        ports:
        - containerPort: 3000
